Improve error message for scope
r-lib/styler pull request #1176
Opened 2024-01-31 14:24 UTC by olivroy

Also fixing some errors I introduced. When linking only to a help page, one should use topic, not help.

2024-01-31 15:25 UTC, lorenzwalthert commented on R/addins.R
> +    abort("Can only style .R, .qmd, .Rmd, and .Rnw files.")
Can we sort alphabetically? First thought we should also standardise casing, but seems like quarto does not encourage or even work with `.Qmd`.

2024-01-31 15:26 UTC, lorenzwalthert commented on R/style-guides.R
> +    scope,
Can you move `scope` one level up?

2024-01-31 15:27 UTC, lorenzwalthert commented on R/transform-code.R
> +    cli::cli_abort("{.path {path}} is not an R, Rmd, qmd, or Rnw file.")
Same order as above I'd prefer.

2024-01-31 15:28 UTC, lorenzwalthert requested changes
Thanks, just minor changes...

2024-01-31 22:33 UTC, IndrajeetPatil commented on R/addins.R
>      rlang::warn(paste(
Maybe also use `cli::cli_warn()` and the inline Markdown formatting here?

2024-02-01 13:40 UTC, olivroy commented
Thanks for your suggestion, I applied them + a couple extra things here and there!

2024-02-02 03:43 UTC, lorenzwalthert approved these changes
Thanks a lot @olivroy.

2024-02-02 06:43 UTC, merged