Complete doc overhaul
r-lib/styler pull request #741
Opened 2021-02-27 19:49 UTC by lorenzwalthert

This PR improves documentation in various ways, in particular: 

* README: 
  * moves adoption and examples out to vignettes. 
  * move feature overview to intro vignette.
  * drop contributing guidelines.
  * updates badges (gh actions, travis appveyor etc).
  * add motivation
* big review of intro to styler vignette and rebranding as 'Get started' article with direct link in navbar, in particular:
  * caching
  * stylerignore
  * dry mode
  * scope specification
  * alignment detection
* caching: better cross-linking and documentation.
* add vignette with examples for `strict = FALSE`.
* add jupyter lab integration to adaption vignette.

2021-02-28 17:01 UTC, jonmcalder commented on vignettes/styler.Rmd
> +- *on*: Like *off*, but not writing back.
```suggestion
- *on*: Applies styling and returns the results without writing changes (if any) back to the file(s).
```

2021-02-28 17:01 UTC, jonmcalder commented on vignettes/styler.Rmd
> +This is enabled by default, you can turn it of with `include_roxygen_examples`.
```suggestion
This is enabled by default, you can turn it off with `include_roxygen_examples = FALSE`.
```

2021-02-28 17:03 UTC, jonmcalder commented on vignettes/strict.Rmd
> +pretty simple for the user to derive it form the bullet or simply paste the
```suggestion
pretty simple for the user to derive it from the bullet point(s) or simply paste the 
```

2021-02-28 17:09 UTC, jonmcalder commented on vignettes/adoption.Rmd
> +You know another way to use styler that is not listed here? Please let us know,
```suggestion
Do you know another way to use styler that is not listed here? Please let us know,
```

2021-02-28 17:09 UTC, jonmcalder commented on vignettes/adoption.Rmd
> +by [opening an issue](https://github.com/r-lib/styler/issues), we'll extend the
```suggestion
by [opening an issue](https://github.com/r-lib/styler/issues) and we'll extend the
```

2021-02-28 17:13 UTC, jonmcalder requested changes
I've suggested a few small changes but overall it looks good to me!

2021-03-03 21:50 UTC, merged

2021-03-03 22:07 UTC, lorenzwalthert commented
Thanks @jonmcalder 🥳